# Generated by Django 5.1.15 on 2026-06-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField(default=0)),
                ('order_no', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('blocks', models.JSONField(default=list)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.topic')),
            ],
            options={
                'ordering': ['topic__code', 'sequence_no'],
                'unique_together': {('topic', 'sequence_no')},
            },
        ),
    ]
