# Generated by Django 5.1.15 on 2026-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studypage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studypage',
            constraint=models.UniqueConstraint(fields=('topic', 'sequence_no'), name='unique_study_page'),
        ),
    ]
