# Generated by Django 5.1.15 on 2026-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practiceresponse',
            name='practice_pr_session_da8f76_idx',
        ),
        migrations.AlterUniqueTogether(
            name='practiceresponse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('random_10', 'Random 10'), ('random_20', 'Random 20'), ('random_30', 'Random 30'), ('unanswered', 'Unanswered'), ('all', 'All')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='practiceresponse',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_practice_response'),
        ),
    ]
