# Generated by Django 5.1.15 on 2026-06-22 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_studypage_unique_together_and_more'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userstudyprogress',
            name='study_users_user_id_381c0c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userstudyprogress',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userstudyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'study_page'), name='unique_user_study_progress'),
        ),
    ]
