# Generated by Django 5.1.15 on 2026-06-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=24)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('pass_status', models.BooleanField(default=False)),
                ('score_percent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockTestQuestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveSmallIntegerField(default=0)),
                ('dwell_time_ms', models.PositiveIntegerField(default=0)),
                ('revisit_count', models.PositiveIntegerField(default=0)),
                ('answer_changed_count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
                ('mock_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mocktest.mocktestsession')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.answeroption')),
                ('mock_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mocktest.mocktestsession')),
            ],
            options={
                'unique_together': {('mock_session', 'question')},
            },
        ),
    ]
