# Generated by Django 5.1.15 on 2026-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestresponse',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='mocktestresponse',
            index=models.Index(fields=['mock_session', 'question'], name='mocktest_mo_mock_se_67cd97_idx'),
        ),
    ]
