# Generated by Django 5.1.15 on 2026-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_add_flagged_to_response'),
        ('practice', '0002_remove_practiceresponse_practice_pr_session_da8f76_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mocktestresponse',
            name='mocktest_mo_mock_se_67cd97_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mocktestresponse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mocktestresponse',
            constraint=models.UniqueConstraint(fields=('mock_session', 'question'), name='unique_mock_response'),
        ),
    ]
